config/routes.rb
Reppost::Application.routes.draw do
  devise_for :users
  root  :to =>  "pages#index"

  resources :pages
  resources :links
  resources :comments
  resources :votes

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
	# Relationships <3
	belongs_to :user
	has_many :comments
	has_many :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	# attr_accessible :email, :username

	#Relationships <3
	has_many :links
	has_many :comments
	has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	#Relationships <3
	belongs_to :user
	belongs_to :link

	validates :user_id, :uniqueness => { :scope => :link_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!, :only => [:create]

	def create
		@comment = current_user.comments.create params[:comment].permit(:authenticity_token, :message, :link_id)
		redirect_to :back
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

	def show
		@link = Link.find params[:id]
		@comment = Comment.new
	end

	def new
		@link = Link.new

	end

	def create
		@link = Link.new params[:link].permit(:url, :title, :user_id)
		if @link.save
			redirect_to link_path(@link)
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@links = Link.paginate(:page => params[:page], :per_page => 25)
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :authenticate_user!
	def create
		# @vote = current_user.votes.create params[:vote].permit(:authenticity_token, :up, :link_id)
		# redirect_to :back

		@vote = current_user.votes.where(:link_id => params[:vote][:link_id]).first || current_user.votes.create(params[:vote])
		@vote.update_attributes(:up => params[:vote][:up])
		redirect_to :back
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reppost</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Devine Alerts -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!-- Log in or Sign UP Links -->
<% if current_user.present? %>
	<%= link_to 'Sign Out', destroy_user_session_path,	:method => :delete %>
<% else %>
	<%= link_to 'Sign In', new_user_session_path %> | 
	<%= link_to 'Register', new_user_registration_path %>
<% end %>

<!-- New Repost -->
<%= link_to "New Reppost", new_link_path %>

<%= yield %>

</body>
</html>

app/views/links/create.html.erb
<h3>Create Post<h3>

app/views/links/new.html.erb
<h3>New Post</h3>
 <%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/show.html.erb
<h3>Post</h3>
<p><a href="<%= @link.url %>"><%= @link.title %></a></p>

<h4>Comments:</h4>
<div>
  <% @link.comments.each do |comment| %>
  	<p><%= comment.user.id%></p>
    <p><%= comment.message %></p>
  <% end %>
</div>

<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
    <%= f.hidden_field :link_id, :value => @link.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/index.html.erb
<ul>
  <% @links.each do |link| %>
    <li>
      Karma: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %>
    	<%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
    	<%= link_to "●", votes_path(:vote => {:link_id => link.id, :up => nil}), :method => :post %>
    	<%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
    	<p><a href="<%= link.url %>"><%= link.title %></a></p>
    	<p><a href="<%= link_path(link) %>">Comments</a></p>
    </li>
  <% end %>
  <%= will_paginate @links, :page_links => false %>
</ul>